[workspace]
members = [
  "pkarr", "server",
]

# See: https://github.com/rust-lang/rust/issues/90148#issuecomment-949194352
resolver = "2"

[workspace.package]
version = "0.5.0-alpha"

[workspace.metadata.crane]
name = "pkarr"

