# HTTP server configurations.
[http]
# The port number to run the HTTP server on. 
port = 6881

# Internal Mainline node configurations
[mainline]
# Port to run the internal Mainline DHT node on.
port = 6881

# Cache settings
[cache]
# Set the path for the cache storage.
path = "./storage/location"
# Maximum number of SignedPackets to store, before evicting the oldest packets.
size = 1_000_000

# Minimum TTL before attempting to lookup a more recent version of a SignedPacket 
minimum_ttl =  300
# Maximum TTL before attempting to lookup a more recent version of a SignedPacket 
maximum_ttl =  86400

[rate_limiter]
# Set to true if you are running this relay
# behind a reverse proxy, to use smart IP address
# extractors.
# 
# Make sure that your server is not also accessible
# directly, otherwise an attacker can bypass the
# Ip rate limiting by setting the trusted headers to 
# a random IP address on every request.
behind_proxy = false
# Maximum number of requests per second.
burst_size = 10
# Number of seconds after which one request of the quota is replenished.
per_second = 2
