[package]
name = "pkarr"
version = "3.0.0"
authors = ["Nuh <nuh@nuh.dev>"]
edition = "2021"
description = "Public-Key Addressable Resource Records (Pkarr); publish and resolve DNS records over Mainline DHT"
license = "MIT"
repository = "https://git.pkarr.org"
keywords = ["mainline", "dht", "dns", "decentralized", "identity"]

[dependencies]
base32 = "0.5.0"
bytes = "1.7.1"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
self_cell = "1.0.2"
simple-dns = "0.6.1"
thiserror = "1.0.49"
tracing = "0.1.40"
dyn-clone = "1.0.17"
document-features = "0.2.8"
rand = "0.8.5"
once_cell = {version = "1.19.0", default-features = false }
lru = { version = "0.12.3", default-features = false }
flume = { version = "0.11.0", features = ["select", "eventual-fairness", "async"], default-features = false , optional = true }

# feat: relay dependencies
tokio = { version = "1.40.0", optional = true, default-features = false }
# inherited from feat:dht as well.
sha1_smol = { version = "1.0.1", optional = true }

# feat: serde dependencies
serde = { version = "1.0.209", features = ["derive"], optional = true }

# feat: endpoints dependencies
futures-lite = { version = "2.5.0", default-features = false, optional = true }
genawaiter = { version = "0.99.1", default-features = false, features = ["futures03"] }

# feat: tls
rustls = { version = "0.23", default-features = false, features = ["ring"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pubky-timestamp = { version = "0.2.0", default-features = false }

# feat: dht dependencies
mainline = { git = "https://github.com/pubky/mainline", optional = true }

# feat: relay dependencies
reqwest = { version = "0.12.7", features = ["rustls-tls"], optional = true }

# feat: lmdb-cache defendencies
heed = { version = "0.20.0", default-features = false, optional = true }
byteorder = { version = "1.5.0", default-features = false, optional = true }
libc = { version = "0.2.159", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
pubky-timestamp = { version = "0.2.0", default-features = false, features = ["httpdate"] }
js-sys = "0.3.69"
futures = "0.3.30"
getrandom = { version = "0.2", features = ["js"] }
reqwest = "0.12.7"
sha1_smol = "1.0.1"
wasm-bindgen-futures = "0.4.45"

[dev-dependencies]
anyhow = "1.0.93"
axum = "0.7.7"
axum-server = "0.7.1"
postcard = { version = "1.0.10", features = ["alloc"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
clap = { version = "4.4.8", features = ["derive"] }
mockito = "1.4.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
# Clients 
## Use [client::dht::Client]
dht = ["dep:mainline", "dep:flume"]
## Use [client::relay::Client]
relay = ["dep:reqwest", "dep:tokio", "dep:sha1_smol", "dep:flume"]

## Derive serde Serialize/Deserialize for PublicKey
serde = ["dep:serde", "pubky-timestamp/serde", "pubky-timestamp/httpdate"]

# Extra
## Use [LmdbCache]
lmdb-cache = ["dep:heed", "dep:byteorder", "dep:libc"]
## Use [extra::endpoints::EndpointResolver] trait implementation for [Client] and [client::relay::Client]
endpoints = ["dep:futures-lite"]
## Use [reqwest::dns::Resolve] trait implementation for [Client] and [client::relay::Client]
reqwest-resolve = ["dep:reqwest", "endpoints"]
## Implement 
tls = ["rustls", "ed25519-dalek/pkcs8"]
## Create a [reqwest::ClientBuilder] from [Client] or [client::relay::Client]
reqwest-builder = ["tls", "reqwest-resolve"]

## Use all features
full = ["dht", "relay", "serde", "endpoints", "lmdb-cache", "reqwest-resolve", "tls", "reqwest-builder"]

default = ["full"]

[package.metadata.docs.rs]
all-features = true

# [lints.clippy]
unwrap_used = "deny"
