[package]
name = "pkarr"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
ehttp = "0.3.0"
reqwest = { version = "0.11", features = ["blocking"] }
simple-dns = "0.5.5"
url = "2.4.1"
zbase32 = "0.1.2"
thiserror = "1"
rand = "0.8.5"
tokio = { version = "1.32.0", features = ["tokio-macros", "macros"] }
