[package]
name = "pkarr"
version = "0.1.3"
authors = ["Nuh <nuh@nuh.dev>"]
edition = "2021"
description = "Public-Key Addressable Resource Records (Pkarr); publish and resolve DNS records over Mainline DHT"
license = "MIT"
"repository" = "https://github.com/nuhvi/pkarr"
keywords = ["mainline", "dht", "dns", "decentralized", "identity"]
categories = ["networking", "p2p", "routing"]

[dependencies]
bytes = "1.5.0"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
rand = "0.8.5"
reqwest = { version = "0.11", features = ["blocking"] }
self_cell = "1.0.1"
simple-dns = "0.5.6"
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["tokio-macros", "macros"] }
url = "2.4.1"
zbase32 = "0.1.2"
