[package]
name = "pkarr"
version = "3.0.0"
authors = ["Nuh <nuh@nuh.dev>"]
edition = "2021"
description = "Public-Key Addressable Resource Records (Pkarr); publish and resolve DNS records over Mainline DHT"
license = "MIT"
repository = "https://git.pkarr.org"
keywords = ["mainline", "dht", "dns", "decentralized", "identity"]

[dependencies]
base32 = "0.5.0"
bytes = "1.7.1"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
self_cell = "1.0.2"
simple-dns = "0.6.1"
thiserror = "1.0.49"
tracing = "0.1.40"
dyn-clone = "1.0.17"
once_cell = {version = "1.19.0", default-features = false }
lru = { version = "0.12.3", default-features = false }
document-features = "0.2.8"
rand = "0.8.5"

# optional dependencies
serde = { version = "1.0.209", features = ["derive"], optional = true }
futures = { version = "0.3.30", optional = true, default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# Dht client dependencies:
mainline = { git = "https://github.com/pubky/mainline", branch = "dev", optional = true }
flume = { version = "0.11.0", features = ["select", "eventual-fairness", "async"], default-features = false , optional = true }
tokio = { version = "1.40.0", optional = true }
reqwest = { version = "0.12.7", features = ["rustls-tls"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.69"
futures = "0.3.30" 
getrandom = { version = "0.2", features = ["js"] }
reqwest = "0.12.7"

[dev-dependencies]
postcard = { version = "1.0.10", features = ["alloc"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
clap = { version = "4.4.8", features = ["derive"] }
mockito = "1.4.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
## Derive serde Serialize/Deserialize for PublicKey
serde = ["dep:serde"]

# Clients 
## Use [dht::Client]
dht = ["dep:mainline", "flume"]
## Use [relay::Client]
relay = ["dep:reqwest", "dep:tokio"]

# Extra
## Use [Client::resolve_endpoints] and [Client::resolve_https_endpoints]
endpoints = ["dep:futures"]

## Use all features
full = ["dht", "relay", "serde", "endpoints"]

default = ["dht", "relay", "serde"]

[package.metadata.docs.rs]
all-features = true

# [lints.clippy]
# unwrap_used = "deny"
