[package]
name = "pkarr"
version = "2.0.0-rc2"
authors = ["Nuh <nuh@nuh.dev>"]
edition = "2021"
description = "Public-Key Addressable Resource Records (Pkarr); publish and resolve DNS records over Mainline DHT"
license = "MIT"
repository = "https://github.com/nuhvi/pkarr"
keywords = ["mainline", "dht", "dns", "decentralized", "identity"]

[dependencies]
bytes = "1.5.0"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
self_cell = "1.0.2"
simple-dns = "0.6.1"
thiserror = "1.0.49"
tracing = "0.1.40"
z32 = "1.1.1"
rand = "0.8.5"
lru = { version = "0.12.3", default-features = false, optional = true }

# Relay client dependencies
futures = { version = "0.3.29", optional = true }
url = { version = "2.5.0", optional = true }
reqwest = { version = "0.12.4", optional = true }

# Dht client dependencies:
mainline = { version = "2.0.0", optional = true }
dyn-clone = { version = "1.0.17", optional = true }
flume = { version = "0.11.0", features = ["select", "eventual-fairness"], default-features = false, optional = true }

[dev-dependencies]
clap = { version = "4.4.8", features = ["derive"] }
mockito = "1.4.0"
tokio = { version = "1.37.0", features = ["rt", "macros"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
# Use [PkarrClient]
dht = ["dep:mainline", "dep:lru", "dep:dyn-clone", "dep:flume"]
# Use [PkarrClientAsync]
async = ["flume/async"]
# Use [PkarrRelayClient]
relay = ["dep:reqwest", "dep:futures", "dep:url"]

full = ["dht", "async", "relay"]

default = ["full"]

[package.metadata.docs.rs]
all-features = true
