[package]
name = "pkarr"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
rand = "0.8.5"
reqwest = { version = "0.11", features = ["blocking"] }
self_cell = "1.0.1"
simple-dns = { git = "https://github.com/balliegojr/simple-dns" }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["tokio-macros", "macros"] }
url = "2.4.1"
zbase32 = "0.1.2"
